"""bind relationship between user with goals

Revision ID: 95a8506ed336
Revises: 5e7c146d0d96
Create Date: 2023-10-28 22:33:36.086174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '95a8506ed336'
down_revision: Union[str, None] = '5e7c146d0d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    op.drop_table('goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
