"""update create, update, del date to user and goal table"

Revision ID: d5495d7f55e8
Revises: a76342f1d4c3
Create Date: 2023-10-28 23:46:02.780242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd5495d7f55e8'
down_revision: Union[str, None] = 'a76342f1d4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('create_date', sa.String(length=120), nullable=False))
    op.add_column('goal', sa.Column('update_date', sa.String(length=120), nullable=True))
    op.add_column('goal', sa.Column('del_date', sa.String(length=120), nullable=True))
    
    op.add_column('user', sa.Column('create_date', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('update_date', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('del_date', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass